// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// tft_driver_pio //
// -------------- //

#define tft_driver_pio_wrap_target 0
#define tft_driver_pio_wrap 17

#define tft_driver_pio_offset_start_wr16 0u
#define tft_driver_pio_offset_start_wr8 7u
#define tft_driver_pio_offset_start_rd8 15u

static const uint16_t tft_driver_pio_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1     
    0x6028, //  1: out    x, 8                       
    0x7108, //  2: out    pins, 8         side 0 [1] 
    0xb842, //  3: nop                    side 1     
    0xa0e1, //  4: mov    osr, x                     
    0x7008, //  5: out    pins, 8         side 0     
    0x0000, //  6: jmp    0                          
    0x9aa0, //  7: pull   block           side 1 [2] 
    0x7108, //  8: out    pins, 8         side 0 [1] 
    0x0007, //  9: jmp    7                          
    0xe700, // 10: set    pins, 0                [7] 
    0xa0c2, // 11: mov    isr, y                     
    0x4008, // 12: in     pins, 8                    
    0xe001, // 13: set    pins, 1                    
    0x8720, // 14: push   block                  [7] 
    0x004a, // 15: jmp    x--, 10                    
    0x80a0, // 16: pull   block                      
    0x0010, // 17: jmp    16                         
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program tft_driver_pio_program = {
    .instructions = tft_driver_pio_program_instructions,
    .length = 18,
    .origin = -1,
};

static inline pio_sm_config tft_driver_pio_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + tft_driver_pio_wrap_target, offset + tft_driver_pio_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

